import Link from "next/link";

export default function Footer() {
  return (
    <footer className="bg-slate-900 text-slate-400">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-10">
          {/* Brand */}
          <div>
            <div className="text-xl font-bold mb-3">
              <span className="text-white">Den</span><span className="text-brand-400">AI</span>
            </div>
            <p className="text-sm leading-relaxed">
              AI-powered insurance appeal letters. Fight back. 80% of appeals win.
            </p>
          </div>

          {/* Links */}
          <div>
            <h3 className="text-white text-sm font-semibold mb-3 uppercase tracking-wider">Product</h3>
            <ul className="space-y-2 text-sm">
              <li>
                <Link href="/#how-it-works" className="hover:text-white transition-colors">
                  How It Works
                </Link>
              </li>
              <li>
                <Link href="/#who-its-for" className="hover:text-white transition-colors">
                  Who It&apos;s For
                </Link>
              </li>
              <li>
                <Link href="/pricing" className="hover:text-white transition-colors">
                  Pricing
                </Link>
              </li>
              <li>
                <Link href="/demo" className="hover:text-white transition-colors">
                  Try Demo
                </Link>
              </li>
            </ul>
          </div>

          {/* Contact */}
          <div>
            <h3 className="text-white text-sm font-semibold mb-3 uppercase tracking-wider">Get Access</h3>
            <p className="text-sm mb-3">Ready to start fighting back?</p>
            <Link
              href="/demo"
              className="inline-block px-4 py-2 text-sm font-semibold rounded-lg bg-brand-600 text-white hover:bg-brand-700 transition-colors"
            >
              Try the Demo →
            </Link>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="border-t border-slate-800 pt-8">
          <p className="text-xs text-slate-500 leading-relaxed mb-4">
            <strong className="text-slate-400">Legal Disclaimer:</strong> DenAI is not a law firm and does not provide legal advice. The appeal letters generated by this tool are for informational purposes only and should not be construed as legal or medical advice. DenAI does not guarantee any specific outcome or the success of any insurance appeal. Users should consult with a qualified healthcare attorney or licensed insurance professional for advice specific to their situation. All content generated is based on publicly available clinical guidelines and general best practices. Use of this tool does not create an attorney-client relationship.
          </p>
          <p className="text-xs text-slate-600">
            © {new Date().getFullYear()} DenAI. All rights reserved. This is a product demonstration.
          </p>
        </div>
      </div>
    </footer>
  );
}
